[package]
name = "c14"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
git2 = "0.20.2"
anyhow = "1.0.98"
#regex = "1.11.1"
conventional = "0.5.0"
openssl-sys = "0.9.109"
regex = "1.11.1"