[package]
name = "c14"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
git2 = "0.20.2"
anyhow = "1.0.98"
conventional = "0.5.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
